var toc_content = `ARTIFICIAL INTELLIGENCE AND CYBERSECURITY RESEARCH 
 
 
3 
 
TABLE OF CONTENTS 
EXECUTIVE SUMMARY 
5 
TOP 5 RESEARCH NEEDS FOR AI AND CYBERSECURITY 
7 
DEFINITION OF TERMS AND ABBREVIATIONS 
8 
KEY AI CONCEPTS AND FEATURES 
10 
1.1 TRADITIONAL ML 
10 
1.1.1 Decision Trees (DT) 
11 
1.1.2 Support vector machines (SVM) 
11 
1.1.3 Naive Bayes’ classifier (NB) 
12 
1.1.4 K-means clustering (Clustering) 
12 
1.1.5 Hidden Markov Model (HMM) 
12 
1.1.6 Genetic algorithms (GA) 
13 
1.2 NEURAL NETWORKS 
13 
1.2.1 Artificial neural Networks (ANNs) 
13 
1.2.2 Convolutional Neural Networks (CNNs) 
14 
1.2.3 Recurrent Neural Networks (RNNs) 
14 
1.2.4 Autoencoders 
14 
1.2.5 Siamese Neural Networks (SNN) 
15 
1.2.6 Ensemble methods 
15 
1.3 RELEVANCE OF DEEP LEARNING (DL)-BASED APPROACHES 
16 
1.4 COMMONLY-USED CYBERSECURITY DATA SETS 
17 
AI IN CYBERSECURITY 
19 
1.5 EXAMPLES OF USE-CASES 
20 
1.5.1 Prevention 
20 
1.5.2 Detection 
21 
SECURING AI 
23 
1.6 AI SECURITY 
23 
1.7 AI-POWERED CYBERATTACKS 
24 
1.8 DEFENDING AI-BASED MECHANISMS 
24 

ARTIFICIAL INTELLIGENCE AND CYBERSECURITY RESEARCH 
 
 
4 
 
SELECTED CASE STUDIES 
26 
1.9 NEXT GENERATION OF TELCOMMUNICATIONS 
26 
1.10  INTERNET OF THINGS (IOT) AND INTERNET OF EVERYTHING (IOE) 
27 
1.11  CYBERSECURITY IN CYBER-PHYSICAL SYSTEMS (CPS) 
28 
1.12  CYBER BIOSECURITY 
29 
AI IN CYBERSECURITY - RESEARCH GAPS AND NEEDS 
31 
1.13  OPEN ISSUES AND CHALLENGES 
31 
1.14  RESEARCH GAPS 
32 
1.15  RESEARCH NEEDS 
33 
CONCLUSIONS AND NEXT STEPS 
38 
 

`;