var toc_content = `(15).
(12)
The notion of ‘AI system’ in this Regulation should be clearly defined and should be closely aligned with the work of 
international organisations working on AI to ensure legal certainty, facilitate international convergence and wide 
acceptance, while providing the flexibility to accommodate the rapid technological developments in this field. 
Moreover, the definition should be based on key characteristics of AI systems that distinguish it from simpler 
traditional software systems or programming approaches and should not cover systems that are based on the rules 
defined solely by natural persons to automatically execute operations. A key characteristic of AI systems is their 
capability to infer. This capability to infer refers to the process of obtaining the outputs, such as predictions, content, 
recommendations, or decisions, which can influence physical and virtual environments, and to a capability of AI 
systems to derive models or algorithms, or both, from inputs or data. The techniques that enable inference while 
building an AI system include machine learning approaches that learn from data how to achieve certain objectives, 
and logic- and knowledge-based approaches that infer from encoded knowledge or symbolic representation of the 
task to be solved. The capacity of an AI system to infer transcends basic data processing by enabling learning, 
reasoning or modelling. The term ‘machine-based’ refers to the fact that AI systems run on machines. The reference 
to explicit or implicit objectives underscores that AI systems can operate according to explicit defined objectives or 
to implicit objectives. The objectives of the AI system may be different from the intended purpose of the AI system 
in a specific context. For the purposes of this Regulation, environments should be understood to be the contexts in 
which the AI systems operate, whereas outputs generated by the AI system reflect different functions performed by 
AI systems and include predictions, content, recommendations or decisions. AI systems are designed to operate with 
varying levels of autonomy, meaning that they have some degree of independence of actions from human 
involvement and of capabilities to operate without human intervention. The adaptiveness that an AI system could 
exhibit after deployment, refers to self-learning capabilities, allowing the system to change while in use. AI systems 
can be used on a stand-alone basis or as a component of a product, irrespective of whether the system is physically 
integrated into the product (embedded) or serves the functionality of the product without being integrated therein 
(non-embedded).
(13)
The notion of ‘deployer’ referred to in this Regulation should be interpreted as any natural or legal person, including 
a public authority, agency or other body, using an AI system under its authority, except where the AI system is used 
in the course of a personal non-professional activity. Depending on the type of AI system, the use of the system may 
affect persons other than the deployer.
(14)
The notion of ‘biometric data’ used in this Regulation should be interpreted in light of the notion of biometric data 
as defined in Article 4, point (14) of Regulation (EU) 2016/679, Article 3, point (18) of Regulation (EU) 2018/1725 
and Article 3, point (13) of Directive (EU) 2016/680. Biometric data can allow for the authentication, identification 
or categorisation of natural persons and for the recognition of emotions of natural persons.
(15)
The notion of ‘biometric identification’ referred to in this Regulation should be defined as the automated recognition 
of physical, physiological and behavioural human features such as the face, eye movement, body shape, voice, 
prosody, gait, posture, heart rate, blood pressure, odour, keystrokes characteristics, for the purpose of establishing an 
individual’s identity by comparing biometric data of that individual to stored biometric data of individuals in 
a reference database, irrespective of whether the individual has given its consent or not. This excludes AI systems 
intended to be used for biometric verification, which includes authentication, whose sole purpose is to confirm that 
a specific natural person is the person he or she claims to be and to confirm the identity of a natural person for the 
sole purpose of having access to a service, unlocking a device or having security access to premises.
EN
OJ L, 12.7.2024
4/144
ELI: http://data.europa.eu/eli/reg/2024/1689/oj
(15)
Regulation (EU) 2022/2065 of the European Parliament and of the Council of 19 October 2022 on a Single Market For Digital 
Services and amending Directive 2000/31/EC (Digital Services Act) (OJ L 277, 27.10.2022, p. 1).


`;