var toc_content = `Article 17;
(d) keep the documentation referred to in Article 18;
(e) when under their control, keep the logs automatically generated by their high-risk AI systems as referred to in 
Article 19;
(f) ensure that the high-risk AI system undergoes the relevant conformity assessment procedure as referred to in Article 43, 
prior to its being placed on the market or put into service;
(g) draw up an EU declaration of conformity in accordance with Article 47;
(h) affix the CE marking to the high-risk AI system or, where that is not possible, on its packaging or its accompanying 
documentation, to indicate conformity with this Regulation, in accordance with Article 48;
(i) comply with the registration obligations referred to in Article 49(1);
(j) take the necessary corrective actions and provide information as required in Article 20;
(k) upon a reasoned request of a national competent authority, demonstrate the conformity of the high-risk AI system with 
the requirements set out in Section 2;
(l) ensure that the high-risk AI system complies with accessibility requirements in accordance with Directives (EU) 
2016/2102 and (EU) 2019/882.
Article 17
Quality management system
1.
Providers of high-risk AI systems shall put a quality management system in place that ensures compliance with this 
Regulation. That system shall be documented in a systematic and orderly manner in the form of written policies, procedures 
and instructions, and shall include at least the following aspects:
(a)
a strategy for regulatory compliance, including compliance with conformity assessment procedures and procedures for 
the management of modifications to the high-risk AI system;
(b) techniques, procedures and systematic actions to be used for the design, design control and design verification of the 
high-risk AI system;
(c)
techniques, procedures and systematic actions to be used for the development, quality control and quality assurance of 
the high-risk AI system;
(d) examination, test and validation procedures to be carried out before, during and after the development of the high-risk 
AI system, and the frequency with which they have to be carried out;
EN
OJ L, 12.7.2024
62/144
ELI: http://data.europa.eu/eli/reg/2024/1689/oj

(e)
technical specifications, including standards, to be applied and, where the relevant harmonised standards are not 
applied in full or do not cover all of the relevant requirements set out in Section 2, the means to be used to ensure that 
the high-risk AI system complies with those requirements;
(f)
systems and procedures for data management, including data acquisition, data collection, data analysis, data labelling, 
data storage, data filtration, data mining, data aggregation, data retention and any other operation regarding the data 
that is performed before and for the purpose of the placing on the market or the putting into service of high-risk AI 
systems;
(g) the risk management system referred to in Article 9;
(h) the setting-up, implementation and maintenance of a post-market monitoring system, in accordance with Article 72;
(i)
procedures related to the reporting of a serious incident in accordance with Article 73;
(j)
the handling of communication with national competent authorities, other relevant authorities, including those 
providing or supporting the access to data, notified bodies, other operators, customers or other interested parties;
(k) systems and procedures for record-keeping of all relevant documentation and information;
(l)
resource management, including security-of-supply related measures;
(m) an accountability framework setting out the responsibilities of the management and other staff with regard to all the 
aspects listed in this paragraph.
2.
The implementation of the aspects referred to in paragraph 1 shall be proportionate to the size of the provider’s 
organisation. Providers shall, in any event, respect the degree of rigour and the level of protection required to ensure the 
compliance of their high-risk AI systems with this Regulation.
3.
Providers of high-risk AI systems that are subject to obligations regarding quality management systems or an 
equivalent function under relevant sectoral Union law may include the aspects listed in paragraph 1 as part of the quality 
management systems pursuant to that law.
4.
For providers that are financial institutions subject to requirements regarding their internal governance, arrangements 
or processes under Union financial services law, the obligation to put in place a quality management system, with the 
exception of paragraph 1, points (g), (h) and (i) of this Article, shall be deemed to be fulfilled by complying with the rules on 
internal governance arrangements or processes pursuant to the relevant Union financial services law. To that end, any 
harmonised standards referred to in Article 40 shall be taken into account.

`;