var toc_content = `67
Dimension: Transparency
6.1  Risk area: transparency in relation to users and affected persons (UA)
This risk area is designed to ensure that users have a clear and suitable explanation/interpretation of how the 
AI application works in order to operate or use it safely, properly and responsibly.
For example, choosing an interpretable model or visualizing explanations of the results in a clear way can help 
achieve transparency. To facilitate this, there are different types of transparency methods that help explain 
which of the input factors are particularly important for the respective output of the AI application. For example, 
doctors using an AI application to diagnose diseases can be shown the sensitivity of the various input parameters 
in the blood count using a heat map. While this would not make things any clearer for a medical layperson 
and especially to the patients as the persons affected, it can make a meaningful contribution to the diagnosis 
for the attending doctors. This is why transparency should be considered in the context of the target group 
being addressed or have customized approaches for different target groups. The technical level of detail of 
the explanation must be specifically adapted to the assumed level of qualification of the users or the affected 
persons.
The internal objectives of the operator may also create additional transparency requirements on top of those 
created by the specific AI application context. For example, companies/organizations can set their own guiding 
principles to provide customers with a high level of transparency regarding the processes they use. Enhanced 
transparency measures that go beyond what is necessary can allow companies/organizations to strengthen the 
trust that customers have in their AI applications (“trust through transparency”).
6.1.1  Risk analysis and objectives
[TR-R-UA-RI-01] Risk analysis and level of transparency of the AI application
Requirement: Do
Risk analysis: An analysis should be performed on the potential damage or hazards that may arise if the 
AI application is not transparent to users or affected persons. Different levels of transparency must be 
considered. In addition, the occurrence probability of the identified potential damage must be estimated.
Objectives: Qualitative objectives are set for the transparency of the AI application based on the risk analysis, 
with reference to the principle of proportionality and considering the typical level of qualification of users and 
affected persons in this application area. Specifically, a description should be provided detailing what level of 
transparency – in terms of interpretability and explainability – is deemed appropriate and is being targeted for 
which part of the AI application, and the reasons behind this.
6.1.2  Criteria for achieving objectives
[TR-R-UA-CR-01] Assessing explainability for users and affected persons
Requirement: Do
Qualitative or quantitative criteria that can be used to meaningfully assess the level of transparency of the 
AI application with respect to users and affected persons should be defined and explained. If different 
criteria is to be used for the circumstances or contexts to be explained to users and affected persons (e.g., 
the data, the model, how the results were established), the choice of criterion must be justified individually 
for each circumstance or context. The choice of criteria can be based on the following list of qualitative 
assessment standards. If other qualitative or quantitative criteria are established, these must be described and 
their selection justified.
 – The clarity and comprehensibility of the explanations given to users and/or affected persons regarding the 
circumstances to be explained (e.g., how the AI application works, data) was confirmed by a significant 
proportion of test affected persons consulted.

68
Dimension: Transparency
 – The clarity and comprehensibility of the explanations given to users and/or affected persons regarding how 
individual outputs are generated or results of the AI application was confirmed by a significant proportion 
of test affected persons consulted.
 – The level of qualification of the test persons consulted corresponds to the level of qualification of the 
anticipated target group or the anticipated users and/or affected persons.
 – The following criteria can serve as a basis for evaluating the explanation of an output given to users and/or 
affected persons (e.g., generated by a transparency method or similar):
 ·
The explanation is valid, in the sense that the transparency method or explanation accurately reflects the 
AI application (e.g., errors in the model, if any, should be reflected as appropriate in the explanation)
 ·
The explanation makes a statement about which input factors are crucial/particularly important for the 
respective output
 ·
The explanation is robust/applicable/consistent in relation to a significant number of similar cases
 ·
The explanation makes a confidence output of the ML model comprehensible for users and/or affected 
persons (see the Risk area: uncertainty estimation (UE) in the Dimension: Reliability (RE))
 ·
The explanation enables the user or affected persons to recognize “new” data points (out-of-domain 
data, in the sense of data points that are not distributed as intended)
 
 
Example: An ML model was trained to detect diseases such as cataracts using close-up images of 
human eyes. A transparency process enables the image areas that are important for the prognosis to 
be highlighted. In this instance, “new” data points in the sense of out-of-domain data could be images 
of a different part of the human body, which are thus not in the intended distribution of input data. 
Conversely, eye images from patients that were not part of the training data are also “unknown” to 
the ML model, but are not out-of-domain data. There are numerous use cases, such as processing raw 
data from a sensor, in which making a distinction between “unknown” data can be difficult for human 
users.
A detailed justification should be provided confirming that the criteria defined here represent the objectives 
set in [TR-R-UA-RI-01].
6.1.3  Measures
6.1.3.1  Data
[TR-R-UA-ME-01] Training and test data
Requirement: Do
Documentation should be available on the training and test data that indicates what kind of data is involved 
and whether it is understandable/interpretable for the intended users or affected persons in view of any prior 
knowledge (related to the intrinsic interpretability of the data). If the data is not intrinsically interpretable, 
then a reason must be provided as to why this particular type of data is being used. Furthermore, there must 
be a description of the measures taken to enable users and affected persons to have a basic understanding of 
the data, for example through documentation or guidance about the data.
 
Example: Image data in which the phenomenon to be investigated by the AI application is clearly 
identifiable should be considered understandable, while raw data from a sensor, particularly if the data is 
high-dimensional, cannot be traced to specific states without substantial effort, so it is not considered 
understandable under this measure.
Any data pre-processing, such as filtering, cleansing or transformation, that is performed before the data is 
used as training or test data must be documented. A check must also be carried out as to whether further 
explanations of these pre-processing steps are necessary for the comprehensibility of the AI application for 
users and/or affected persons. Any explanations provided or justification of why explanations are not provided 
must be documented.

`;