var toc_content = `Reference Links
1. AI Chatbots as Health Information Sources: Misrepresentation of Expertise: KFF
2. Air Canada Chatbot Misinformation: What Travellers Should Know: BBC
3. ChatGPT Fake Legal Cases: Generative AI Hallucinations: LegalDive
4. Understanding LLM Hallucinations: Towards Data Science
5. How Should Companies Communicate the Risks of Large Language Models to Users?:
Techpolicy
6. A news site used AI to write articles. It was a journalistic disaster: Washington Post
7. Diving Deeper into AI Package Hallucinations: Lasso Security
8. How Secure is Code Generated by ChatGPT?: Arvix
9. How to Reduce the Hallucinations from Large Language Models: The New Stack
10. Practical Steps to Reduce Hallucination: Victor Debia
11. A Framework for Exploring the Consequences of AI-Mediated Enterprise Knowledge:
Microsoft

`;