var toc_content = `13 
 
balance competing interests and objectives.31 The procedural dimension of fairness entails the ability to contest and 
seek effective redress against decisions made by AI systems and by the humans operating them.32 In order to do so, 
the entity accountable for the decision must be identifiable, and the decision-making processes should be 
explicable. 
 
The principle of explicability 
Explicability is crucial for building and maintaining users’ trust in AI systems. This means that processes need to be 
transparent, the capabilities and purpose of AI systems openly communicated, and decisions – to the extent 
possible – explainable to those directly and indirectly affected. Without such information, a decision cannot be duly 
contested. An explanation as to why a model has generated a particular output or decision (and what combination 
of input factors contributed to that) is not always possible. These cases are referred to as ‘black box’ algorithms and 
require special attention. In those circumstances, other explicability measures (e.g. traceability, auditability and 
transparent communication on system capabilities) may be required, provided that the system as a whole respects 
fundamental rights. The degree to which explicability is needed is highly dependent on the context and the severity 
of the consequences if that output is erroneous or otherwise inaccurate.33 
 
2.3 Tensions between the principles  
Tensions may arise between the above principles, for which there is no fixed solution. In line with the EU 
fundamental commitment to democratic engagement, due process and open political participation, methods of 
accountable deliberation to deal with such tensions should be established. For instance, in various application 
domains, the principle of prevention of harm and the principle of human autonomy may be in conflict. Consider as 
an example the use of AI systems for ‘predictive policing’, which may help to reduce crime, but in ways that entail 
surveillance activities that impinge on individual liberty and privacy. Furthermore, AI systems’ overall benefits 
should substantially exceed the foreseeable individual risks. While the above principles certainly offer guidance 
towards solutions, they remain abstract ethical prescriptions. AI practitioners can hence not be expected to find the 
right solution based on the principles above, yet they should approach ethical dilemmas and trade-offs via 
reasoned, evidence-based reflection rather than intuition or random discretion.  
There may be situations, however, where no ethically acceptable trade-offs can be identified. Certain fundamental 
rights and correlated principles are absolute and cannot be subject to a balancing exercise (e.g. human dignity).  
Key guidance derived from Chapter I: 
 Develop, deploy and use AI systems in a way that adheres to the ethical principles of: respect for human 
autonomy, prevention of harm, fairness and explicability. Acknowledge and address the potential tensions 
between these principles.  
 Pay particular attention to situations involving more vulnerable groups such as children, persons with 
disabilities and others that have historically been disadvantaged or are at risk of exclusion, and to situations 
which are characterised by asymmetries of power or information, such as between employers and workers, or 
between businesses and consumers.34 
                                                           
31  
This is relates to the principle of proportionality (reflected in the maxim that one should not ‘use a sledge hammer to crack a 
nut’). Measures taken to achieve an end (e.g. the data extraction measures implemented to realise the AI optimisation function) 
should be limited to what is strictly necessary. It also entails that when several measures compete for the satisfaction of an end, 
preference should be given to the one that is least adverse to fundamental rights and ethical norms (e.g. AI developers should 
always prefer public sector data to personal data). Reference can also be made to the proportionality between user and 
deployer, considering the rights of companies (including intellectual property and confidentiality) on the one hand, and the rights 
of the user on the other. 
32  
Including by using their right of association and to join a trade union in a working environment, as provided for by Article 12 of 
the EU Charter of fundamental rights. 
33  
For example, little ethical concern may flow from inaccurate shopping recommendations generated by an AI system, in contrast 
to AI systems that evaluate whether an individual convicted of a criminal offence should be released on parole.  
34  
See articles 24 to 27 of the EU Charter, dealing with the rights of the child and the elderly, the integration of persons with 
disabilities and workers’ rights. See also article 38 dealing with consumer protection.  

`;