var toc_content = `TABLE OF
CONTENTS
DOD DATA, ANALYTICS, AND ARTIFICIAL INTELLIGENCE ADOPTION STRATEGY

FOREWORD 
STRATEGIC ENVIRONMENT
KEY OUTCOMES
STRATEGIC GOALS
IMPLEMENTATION
CONCLUSION
APPENDIX A: QUALITY DATA
DOD DATA, ANALYTICS, AND ARTIFICIAL INTELLIGENCE ADOPTION STRATEGY
2 
3
5
7
14
17
19

`;