const urlData = {
    "AI Act": "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai",
    "AI Management Essentials tool": "https://www.gov.uk/government/consultations/ai-management-essentials-tool",
    "AI Standardisation Landscape   state of play and link to the EC proposal  for an AI regulatory framework": "https://op.europa.eu/en/publication-detail/-/publication/36c46b8e-e518-11eb-a1a5-01aa75ed71a1/language-en",
    "AIを用いたクラウドサービスに関するガイドブック": "https://www.soumu.go.jp/menu_news/s-news/01ryutsu06_02000305.html",
    "AIを用いたクラウドサービスの安全・信頼性に係る情報開示指針(ASP-SaaS編)": "https://www.soumu.go.jp/menu_news/s-news/01ryutsu06_02000306.html",
    "AIセーフティに関するレッドチーミング手法ガイド": "https://www.ipa.go.jp/pressrelease/2024/press20240925.html",
    "AIセーフティに関する評価観点ガイド": "https://www.ipa.go.jp/pressrelease/2024/press20240918-2.html",
    "AIプロダクト品質保証ガイドライン(QA4AI) 2025.04版": "https://www.qa4ai.jp/",
    "AI事業者向けガイドライン (2024.4発行)": "https://www.meti.go.jp/press/2024/04/20240419004/20240419004.html",
    "AI原則実践のためのガバナンス・ガイドライン": "https://www.meti.go.jp/shingikai/mono_info_service/ai_shakai_jisso/2021070902_report.html",
    "AI戦略2022": "https://www8.cao.go.jp/cstp/ai/index.html",
    "Artificial Intelligence and Cybersecurity Research": "https://www.enisa.europa.eu/publications/artificial-intelligence-and-cybersecurity-research",
    "Assuring a Responsible Future for AI": "https://www.gov.uk/government/publications/assuring-a-responsible-future-for-ai",
    "Cybersecurity of AI and Standardisation": "https://www.enisa.europa.eu/publications/cybersecurity-of-ai-and-standardisation",
    "Data Analytics and AI Adoption Strategy": "https://www.war.gov/News/Releases/Release/Article/3577857/deputy-secretary-of-defense-kathleen-hicks-announces-publication-of-data-analyt/",
    "Ethics guidelines for trustworthy AI": "https://digital-strategy.ec.europa.eu/en/library/ethics-guidelines-trustworthy-ai",
    "Fraunhofer AI Assessment Catalog (EN)": "https://www.iais.fraunhofer.de/en/research/artificial-intelligence/ai-assessment-catalog.html",
    "General-Purpose AI Code of Practice the first draft": "https://digital-strategy.ec.europa.eu/en/library/first-draft-general-purpose-ai-code-practice-published-written-independent-experts",
    "German Standardization Roadmap on Artificial Intelligence (2nd edition)": "https://www.din.de/en/innovation-and-research/artificial-intelligence/ai-roadmap#:~:text=The%20Roadmap%20is%20part%20of%20the%20German%20government%27s%20AI%20Strategy",
    "Guide for Preparing and Responding to Deepfake Events": "https://genai.owasp.org/resource/guide-for-preparing-and-responding-to-deepfake-events/",
    "Guidelines for secure AI system development": "https://www.ncsc.gov.uk/collection/guidelines-secure-ai-system-development",
    "Introduction to AI assurance": "https://www.gov.uk/government/publications/introduction-to-ai-assurance/introduction-to-ai-assurance",
    "Joint Statement on Responsible Government Practices for AI Technologies": "https://freedomonlinecoalition.com/joint-statement-on-responsible-government-practices-for-ai-technologies/",
    "LLM and Generative AI Security Center of Excellence Guide": "https://genai.owasp.org/resource/llm-and-generative-ai-security-center-of-excellence-guide/",
    "LLM and Generative AI Security Solutions Landscape": "https://genai.owasp.org/resource/llm-and-generative-ai-security-solutions-landscape/",
    "Memorandum on Advancing the United States’ Leadership in Artificial Intelligence": "https://www.whitehouse.gov/briefing-room/presidential-actions/2024/10/24/memorandum-on-advancing-the-united-states-leadership-in-artificial-intelligence-harnessing-artificial-intelligence-to-fulfill-national-security-objectives-and-fostering-the-safety-security/?tpcc=NL_Marketing",
    "NIST AI 100-1 AI Risk Management Framework (AI RMF 1.0)およびNIST AI RMF Playbook": "https://nvlpubs.nist.gov/nistpubs/ai/nist.ai.100-1.pdf",
    "OWASP Top 10 for LLM Applications 2025": "https://genai.owasp.org/resource/owasp-top-10-for-llm-applications-2025/",
    "Responsible Artificial Intelligence Guideline": "https://www.diu.mil/responsible-ai-guidelines",
    "Responsible Artificial Intelligence strategy and implementation pathway": "https://www.ai.mil/blog_06_22_22_dod_rai_si_pathway_maps_to_trusted_ai_ecosystem.html",
    "Risks and Mitigation Strategies for Adversarial Artificial Intelligence Threats": "https://www.dhs.gov/science-and-technology/publication/risks-and-mitigation-strategies-adversarial-artificial-intelligence-threats",
    "Roles and Responsibilities Framework for Artificial Intelligence in Critical Infrastructure": "https://www.dhs.gov/news/2024/11/14/groundbreaking-framework-safe-and-secure-deployment-ai-critical-infrastructure",
    "Safe and secure innovation for frontier artificial intelligence models act (SB1047)": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB1047",
    "Second Draft GeneralPurpose AI Code of Practice": "https://digital-strategy.ec.europa.eu/en/library/second-draft-general-purpose-ai-code-practice-published-written-independent-experts",
    "Securing ML Algorithms": "https://www.enisa.europa.eu/publications/securing-machine-learning-algorithms",
    "The roadmap to an effective AI assurance ecosystem": "https://www.gov.uk/government/publications/the-roadmap-to-an-effective-ai-assurance-ecosystem",
    "カリフォルニア州 AI関連法案 AB1008": "https://www.jetro.go.jp/biznews/2024/10/ea513ced0c42a432.html",
    "カリフォルニア州 AI関連法案 AB2013": "https://www.jetro.go.jp/biznews/2024/10/ea513ced0c42a432.html",
    "カリフォルニア州 AI関連法案 SB896": "https://www.jetro.go.jp/biznews/2024/10/ea513ced0c42a432.html",
    "デジタル社会の実現に向けた重点計画": "https://www.digital.go.jp/policies/priority-policy-program",
    "フロンティアAIの開発に関する法制度の論点整理": "https://smart-governance.co.jp/2024/11/15/news20241115/",
    "ヘルスケア事業者のための生成AI活用ガイド": "https://jadha.jp/news/news20250207.html",
    "企業活動にAI倫理を導入していく上での注意点と提言_リスクベース・アプローチを踏まえた検討": "https://aibpc.org/",
    "医療デジタルデータのAI研究開発等への利活用に係るガイドライン": "https://www.mhlw.go.jp/content/001310044.pdf",
    "国家人工知能産業総合標準化体系建設ガイドライン（2024版）": "https://www.gov.cn/zhengce/zhengceku/202407/content_6960720.htm",
    "広島AIプロセスに関するG7首脳声明": "https://www.mofa.go.jp/mofaj/ecm/ec/page5_000483.html",
    "機械学習品質マネジメントガイドライン(AIQM) 4.1.0版": "https://www.digiarc.aist.go.jp/publication/aiqm/guideline-rev4.html",
    "生成AIサービス管理暫行弁法": "https://www.bing.com/ck/a?!&&p=35b0822bcab4a546JmltdHM9MTcyNzY1NDQwMCZpZ3VpZD0xMzUyZTdkYS03MGE0LTYwM2ItM2I2OS1mMzVkNzE4NjYxY2MmaW5zaWQ9NTIzNQ&ptn=3&ver=2&hsh=3&fclid=1352e7da-70a4-603b-3b69-f35d718661cc&psq=%e5%9b%bd%e5%ae%b6%e3%82%a4%e3%83%b3%e3%82%bf%e3%83%bc%e3%83%8d%e3%83%83%e3%83%88%e6%83%85%e5%a0%b1%e5%bc%81%e5%85%ac%e5%ae%a4%e3%80%80%e7%94%9f%e6%88%90AI&u=a1aHR0cHM6Ly9jcmRiLmpwL3dwL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDIzLzA3L2NkaWwtMTUtMTAucGRmIzp-OnRleHQ944CO55Sf5oiQ5Z6L5Lq65bel55-l6IO944K144O8&ntb=1",
    "防衛省AI活用推進基本方針(2024.7月)": "https://www.mod.go.jp/j/press/news/2024/07/02a.html"
};