var toc_content = `68
Dimension: Transparency
 – The clarity and comprehensibility of the explanations given to users and/or affected persons regarding how 
individual outputs are generated or results of the AI application was confirmed by a significant proportion 
of test affected persons consulted.
 – The level of qualification of the test persons consulted corresponds to the level of qualification of the 
anticipated target group or the anticipated users and/or affected persons.
 – The following criteria can serve as a basis for evaluating the explanation of an output given to users and/or 
affected persons (e.g., generated by a transparency method or similar):
 ·
The explanation is valid, in the sense that the transparency method or explanation accurately reflects the 
AI application (e.g., errors in the model, if any, should be reflected as appropriate in the explanation)
 ·
The explanation makes a statement about which input factors are crucial/particularly important for the 
respective output
 ·
The explanation is robust/applicable/consistent in relation to a significant number of similar cases
 ·
The explanation makes a confidence output of the ML model comprehensible for users and/or affected 
persons (see the Risk area: uncertainty estimation (UE) in the Dimension: Reliability (RE))
 ·
The explanation enables the user or affected persons to recognize “new” data points (out-of-domain 
data, in the sense of data points that are not distributed as intended)
 
 
Example: An ML model was trained to detect diseases such as cataracts using close-up images of 
human eyes. A transparency process enables the image areas that are important for the prognosis to 
be highlighted. In this instance, “new” data points in the sense of out-of-domain data could be images 
of a different part of the human body, which are thus not in the intended distribution of input data. 
Conversely, eye images from patients that were not part of the training data are also “unknown” to 
the ML model, but are not out-of-domain data. There are numerous use cases, such as processing raw 
data from a sensor, in which making a distinction between “unknown” data can be difficult for human 
users.
A detailed justification should be provided confirming that the criteria defined here represent the objectives 
set in [TR-R-UA-RI-01].
6.1.3  Measures
6.1.3.1  Data
[TR-R-UA-ME-01] Training and test data
Requirement: Do
Documentation should be available on the training and test data that indicates what kind of data is involved 
and whether it is understandable/interpretable for the intended users or affected persons in view of any prior 
knowledge (related to the intrinsic interpretability of the data). If the data is not intrinsically interpretable, 
then a reason must be provided as to why this particular type of data is being used. Furthermore, there must 
be a description of the measures taken to enable users and affected persons to have a basic understanding of 
the data, for example through documentation or guidance about the data.
 
Example: Image data in which the phenomenon to be investigated by the AI application is clearly 
identifiable should be considered understandable, while raw data from a sensor, particularly if the data is 
high-dimensional, cannot be traced to specific states without substantial effort, so it is not considered 
understandable under this measure.
Any data pre-processing, such as filtering, cleansing or transformation, that is performed before the data is 
used as training or test data must be documented. A check must also be carried out as to whether further 
explanations of these pre-processing steps are necessary for the comprehensibility of the AI application for 
users and/or affected persons. Any explanations provided or justification of why explanations are not provided 
must be documented.

69
Dimension: Transparency
6.1.3.2  AI component
[TR-R-UA-ME-02] Interpretability of the ML model
Requirement: Do
Documentation regarding which models were considered to address the present problem must be available. 
In addition, it must be demonstrated that these models have been evaluated in terms of their interpretability, 
e.g., by in-depth analysis of the choice of architecture, thus examining the possible operations and their 
possible sequence.
Documentation should be available describing why the model (or architecture) was chosen. If no interpretable 
model is used, it must be made clear why no such model is used. The list below provides a selection of models 
considered interpretable at the time when this catalog was published.
Interpretable models46 include (as of July 2021):
Linear and logistic regression (as well as their extensions including generalized linear models and generalized 
additive models)
Linear and logistic classification
Decision trees
Rule learning
Naive Bayesian classifier
K-nearest neighbor
[TR-R-UA-ME-03] Traceability of how the application works
Requirement: Do
Documentation and/or a visualization of the model (including a schematic diagram of the architecture, if 
applicable) must be available that contains sufficient explanations to make the way the application works 
comprehensible. There is an outline of how this visualization or explanation will be made available to users 
and affected persons of the AI application.
[TR-R-UA-ME-04] How the results are generated
Requirement: Do
Documentation should be available describing the measures taken to explain how results are generated. The 
type and scope of the explanations must always be chosen based on proportionality, taking into account the 
level of qualification of users and affected persons as well as their use of the AI application. For example, 
explanations might be useful for users but might be excessive for other affected persons of the same 
AI application.
In the case of models that are intrinsically interpretable:
 – For rule-based models, it is necessary to specify which rules apply to the current decision (e.g., in the case 
of decision trees, the branching selected could be displayed next to the result).
 – For linear regression and related models, it is necessary to specify the most relevant or crucial attributes for 
making a decision (the largest absolute value of the coefficients for normalized inputs).
For black box models:
 
Methods used to create explanations or support interpretability should be described. Methods should either 
be model-specific or model-agnostic, as in the sample methods listed below:
 – Partial dependence plots
 – Individual conditional expectation plots
46  According to: Molnar, C. (June 2021). Chapter 4 Interpretable Models | Interpretable Machine Learning: A Guide for Making Black Box 
Models Explainable. https://christophm.github.io/interpretable-ml-book/simple.html (last accessed: 06/16/2021)

`;