var toc_content = `This section contains guidelines that apply to the development stage of the AI system development 
lifecycle, including supply chain security, documentation, and asset and technical debt management.
Secure your supply chain
You assess and monitor the security of your AI supply chains across a system’s life cycle, and require 
suppliers to adhere to the same standards your own organisation applies to other software. If 
suppliers cannot adhere to your organisation’s standards, you act in accordance with your existing risk 
management policies.
Where not produced in-house, you acquire and maintain well-secured and well-documented hardware 
and software components (for example, models, data, software libraries, modules, middleware, 
frameworks, and external APIs) from verified commercial, open source, and other third-party developers to 
ensure robust security in your systems.
You are ready to failover to alternate solutions for mission-critical systems, if security criteria are not met. 
You use resources like the NCSC’s Supply Chain Guidance and frameworks such as Supply Chain Levels 
for Software Artifacts (SLSA)10 for tracking attestations of the supply chain and software development life 
cycles.
Identify, track and protect your assets
You understand the value to your organisation of your AI-related assets, including models, data 
(including user feedback), prompts, software, documentation, logs and assessments (including 
information about potentially unsafe capabilities and failure modes), recognising where they represent 
significant investment and where access to them enables an attacker. You treat logs as sensitive data 
and implement controls to protect their confidentiality, integrity and availability. 
You know where your assets reside and have assessed and accepted any associated risks. You have 
processes and tools to track, authenticate, version control and secure your assets, and can restore to a 
known good state in the event of compromise.
You have processes and controls in place to manage what data AI systems can access, and to manage 
content generated by AI according to its sensitivity (and the sensitivity of the inputs that went into 
generating it).
Document your data, models and prompts
You document the creation, operation, and life cycle management of any models, datasets and meta- 
or system-prompts. Your documentation includes security-relevant information such as the sources 
of training data (including fine-tuning data and human or other operational feedback), intended 
scope and limitations, guardrails, cryptographic hashes or signatures, retention time, suggested review 
frequency and potential failure modes. Useful structures to help do this include model cards, data cards 
and software bills of materials (SBOMs). The production of comprehensive documentation supports 
transparency and accountability11.
12
2. Secure development
Guidelines for secure AI system development

Manage your technical debt
As with any software system, you identify, track and manage your ‘technical debt’ throughout an AI 
system’s life cycle (technical debt is where engineering decisions that fall short of best practices to 
achieve short-term results are made, at the expense of longer-term benefits). Like financial debt, 
technical debt is not inherently bad, but should be managed from the earliest stages of development12. 
You recognise that doing so can be more challenging in an AI context than for standard software, and 
that your levels of technical debt are likely to be high due to rapid development cycles and a lack of 
well-established protocols and interfaces. You ensure your life cycle plans (including processes to 
decommission AI systems) assess, acknowledge and mitigate risks to future similar systems. 
13
Guidelines for secure AI system development

14
This section contains guidelines that apply to the deployment stage of the AI system development life 
cycle, including protecting infrastructure and models from compromise, threat or loss, developing incident 
management processes, and responsible release.

Secure your infrastructure
You apply good infrastructure security principles to the infrastructure used in every part of your system’s 
life cycle. You apply appropriate access controls to your APIs, models and data, and to their training and 
processing pipelines, in research and development as well as deployment. This includes appropriate 
segregation of environments holding sensitive code or data. This will also help mitigate standard cyber 
security attacks which aim to steal a model or harm its performance. 
Protect your model continuously
Attackers may be able to reconstruct the functionality of a model13 or the data it was trained on14, by 
accessing a model directly (by acquiring model weights) or indirectly (by querying the model via an 
application or service). Attackers may also tamper with models, data or prompts during or after training, 
rendering the output untrustworthy. 
You protect the model and data from direct and indirect access, respectively, by:
 >
implementing standard cyber security best practices
 >
implementing controls on the query interface to detect and prevent attempts to access, modify, and 
exfiltrate confidential information
To ensure that consuming systems can validate models, you compute and share cryptographic hashes 
and/or signatures of model files (for example, model weights) and datasets (including checkpoints) as 
soon as the model is trained. As always with cryptography, good key management is essential15.

Your approach to confidentiality risk mitigation will depend considerably on the use case and the threat 
model. Some applications, for example those involving very sensitive data, may require theoretical 
guarantees that can be difficult or expensive to apply. If appropriate, privacy-enhancing technologies 
(such as differential privacy or homomorphic encryption) can be used to explore or assure levels of risk 
associated with consumers, users and attackers having access to models and outputs.
3. 
`;