var toc_content = `What AIME looks like 
We expect the final version of AIME to include three components: 
1. A self-assessment questionnaire; 
2. A rating for each section of the self-assessment, to provide users with a concise view 
of their AI management system health, calculated on self-assessment answers; 
3. A set of action points and recommendations for improvement, generated by self-
assessment answers. 
Only the self-assessment questionnaire is included in this consultation. The ratings and 
recommendations will be developed by DSIT following this consultation. The outputs will be 
made available alongside the final version of the AIME tool. 
AIME is organised into three thematic areas:  
• Internal processes: these questions assess the overarching structures and principles 
underlying your AI management system. 
• Managing risks: these questions assess the processes through which you prevent, 
manage, and mitigate risks. 
• Communication: these questions assess your communication with employees, 
external users and interested parties. 
Each section begins with a motivating statement to represent good practice that the following 
questions are designed to interrogate.  
 

`;